In [9]:
import pandas as pd
from datetime import datetime
import os

In [16]:
results = pd.read_csv('results_4_14')
# results2 = pd.read_csv('results_4_15')
# results3 = pd.read_csv('results_4_16')
# results4 = pd.read_csv('results_4_17')
# frames = [results1, results2, results3, results4]
# results = pd.concat(frames)

for filename in os.listdir(./daily_results):
    if filename != "results_4_14":
        results_j = pd.read_csv('filename')
        results = pd.concat(results_j)





results.drop(results.columns[0], axis=1, inplace=True)
results['year'] = datetime.now().year
results['date'] = pd.to_datetime(results[['year', 'month', 'day']])
results.drop(['month', 'day', 'year', 'predicted.run.rank', 'predicted.bookie.rank'], axis=1, inplace=True)

print("Profit since tracking began on April 14:")
print()
# Report 1:  Running total of just betting the best daily bet
report1 = results.groupby('date').apply(lambda t: t[t['betting.opportunity'] == t['betting.opportunity'].max()])
print("Bet the best bet each day:", report1['bet.result'].sum())

# Report 2:  Running total of betting every game for which we have data
print("Bet every game each day:", results['bet.result'].sum())

# Report 3:  Bet the Cubs games only
report3 = results[(results['home'] == "CHC") | (results['away'] == "CHC")]
print("Bet only the Cubs games:", report3['bet.result'].sum())
print()

results

Profit since tracking began on April 14:

Bet the best bet each day: -100
Bet every game each day: -200
Bet only the Cubs games: 0

,away,home,predicted.runs,bookie,outcome,the.bet,betting.opportunity,game.result,bet.result,date
0,PIT,WSH,10.165955,7.5,7,OVER,6.5,UNDER,-100,2019-04-14
1,TB,TOR,8.391426,8.0,12,UNDER,5.5,OVER,-100,2019-04-14
2,DET,MIN,9.747278,7.5,10,OVER,4.5,OVER,100,2019-04-14
3,MIL,LAD,9.580962,9.0,8,UNDER,4.5,UNDER,100,2019-04-14
4,SD,ARI,8.856418,8.0,12,UNDER,4.5,OVER,-100,2019-04-14
5,CLE,KC,9.653182,7.5,17,OVER,3.5,OVER,100,2019-04-14
6,COL,SF,9.415460,7.0,4,OVER,3.0,UNDER,-100,2019-04-14
7,CWS,NYY,10.255672,9.0,7,OVER,2.5,UNDER,-100,2019-04-14
8,NYM,ATL,9.644266,8.5,10,UNDER,2.0,OVER,-100,2019-04-14
9,BAL,BOS,10.017261,9.5,4,UNDER,2.0,UNDER,100,2019-04-14
10,OAK,TEX,10.188104,10.0,15,UNDER,1.0,OVER,-100,2019-04-14
11,HOU,SEA,9.013162,7.5,5,UNDER,0.5,UNDER,100,2019-04-14